import type {
  AlertConfig,
  AllocationItem,
  BillingSummary,
  CoinbaseConnection,
  DashboardSummary,
  TokenItem,
  TradingMode,
} from "@/lib/dashboard-types";

const baseGrowthPaper = [100, 101, 102, 102.4, 103.3, 104.1, 104.8, 105.4, 106.2, 106.8, 107.1, 107.9];
const baseGrowthLive = [100, 99.2, 100.3, 101.8, 100.9, 102.1, 102.7, 101.9, 103.4, 104.6, 103.8, 105.2];

export function mockDashboard(mode: TradingMode): DashboardSummary {
  const isLive = mode === "live";
  return {
    availableBalance: isLive ? 18214.64 : 6240.31,
    portfolioValue: isLive ? 52743.12 : 18290.44,
    pnlValue: isLive ? 1248.11 : 612.09,
    realizedPnlValue: isLive ? 902.21 : 401.12,
    unrealizedPnlValue: isLive ? 345.9 : 210.97,
    pnlPercent: isLive ? 2.42 : 3.46,
    gainLossLabel: "Total P&L",
    growth: isLive ? baseGrowthLive : baseGrowthPaper,
    positionsCount: 2,
    activeTradesCount: 2,
    recentActivityCount: 3,
    totalFeesMonth: isLive ? 221.9 : 84.47,
    avgNetEdgeAtEntryBps: isLive ? 46.8 : 61.4,
    totalRejected: isLive ? 14 : 6,
    enabledStrategies: [
      { id: "momentum", name: "Momentum", enabled: true, allocationPct: 42 },
      { id: "dca", name: "DCA", enabled: true, allocationPct: 28 },
      { id: "day-trading", name: "Day Trading", enabled: !isLive, allocationPct: 12 },
      { id: "mean-reversion", name: "Mean Reversion", enabled: isLive, allocationPct: 18 },
    ],
    strategyHealth: [
      {
        id: "momentum",
        name: "Momentum",
        enabled: true,
        allocationPct: 42,
        assignedCapital: isLive ? 18900 : 6300,
        availableCash: isLive ? 7400 : 2400,
        deployedCapital: isLive ? 11500 : 3900,
        utilizationPct: isLive ? 60.85 : 61.9,
        realizedPnl: isLive ? 810.2 : 290.4,
        unrealizedPnl: isLive ? 392 : 281,
        currentStatus: "managing_position",
        openPositions: 1,
        lastEvaluatedAt: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
        lastSignalAt: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
        lastSignalAction: "buy",
        lastSignalReason: "Momentum confirmation passed",
        lastTradeAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
        lastBuyAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
        dcaIntervalHours: null,
        exitMonitoredPositions: 1,
        stalledExitCount: isLive ? 1 : 0,
        latestExitAt: new Date(Date.now() - 1000 * 60 * 6).toISOString(),
        latestExitReasonCode: isLive ? "exit_stalled" : "take_profit_triggered",
        latestExitReasonDetail: isLive
          ? "1 exit request looks stale and should be reviewed."
          : "Take-profit guard is armed and monitoring the open BTC position.",
        blockingReasonCode: isLive ? "exit_stalled" : "take_profit_triggered",
        blockingReasonDetail: isLive
          ? "1 exit request looks stale and should be reviewed."
          : "Take-profit guard is armed and monitoring the open BTC position.",
        nextEligibleAt: null,
        latestLifecycleStage: "take_profit_triggered",
        latestLifecycleStatus: "observed",
      },
      {
        id: "dca",
        name: "DCA",
        enabled: true,
        allocationPct: 28,
        assignedCapital: isLive ? 11760 : 4200,
        availableCash: isLive ? 5300 : 1980,
        deployedCapital: isLive ? 6460 : 2220,
        utilizationPct: isLive ? 54.93 : 52.86,
        realizedPnl: isLive ? 122.4 : 61.2,
        unrealizedPnl: isLive ? -54 : 62,
        currentStatus: "waiting",
        openPositions: 1,
        lastEvaluatedAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
        lastSignalAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
        lastSignalAction: "hold",
        lastSignalReason: "Waiting for next DCA interval",
        lastTradeAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
        lastBuyAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
        dcaIntervalHours: 24,
        exitMonitoredPositions: 0,
        stalledExitCount: 0,
        latestExitAt: null,
        latestExitReasonCode: null,
        latestExitReasonDetail: null,
        blockingReasonCode: "cooldown_active",
        blockingReasonDetail: "Waiting for next DCA interval.",
        nextEligibleAt: new Date(Date.now() + 1000 * 60 * 60 * 6).toISOString(),
        latestLifecycleStage: "cooldown_validation",
        latestLifecycleStatus: "failed",
      },
    ],
    botHealth: {
      overallStatus: isLive ? "warning" : "healthy",
      runtimeStatus: isLive ? "warning" : "healthy",
      pipelineStatus: "active",
      mode,
      activeStrategies: 4,
      activePositions: 2,
      criticalDiagnosticsCount: isLive ? 1 : 0,
      lastSuccessfulTradeAt: new Date(Date.now() - 1000 * 60 * 38).toISOString(),
      quietReasonCode: "managing_open_positions",
      quietReason: "Bot is actively managing open positions while waiting for the next qualified setups.",
      marketData: {
        status: "fresh",
        lastAt: new Date(Date.now() - 1000 * 18).toISOString(),
        ageSeconds: 18,
        tradeTicksRecent: 420,
        bboUpdatesRecent: 910,
      },
      reconciliation: {
        status: isLive ? "warning" : "healthy",
        mismatchCount: isLive ? 1 : 0,
        scopeCount: 4,
        bucketCount: 4,
        externalErrorCount: 0,
        topMismatchTypes: isLive ? [{ type: "bucket_locked_capital_mismatch", count: 1 }] : [],
      },
      paperLive: {
        currentMode: mode,
        canSwitchToLive: !isLive,
        liveReadinessReason: isLive ? null : "Valid Coinbase connection with trading and balance permissions is required for live trading",
        strictPaperModeAvailable: false,
        paperWarning: "Paper results may not fully represent live trading conditions.",
        connectionStatus: isLive ? "healthy" : "not_connected",
        checklist: [
          {
            id: "reconciliation",
            label: "Reconciliation healthy",
            passed: !isLive,
            detail: !isLive ? "Execution, position, and capital buckets reconcile cleanly." : "1 mismatch needs review.",
          },
          {
            id: "diagnostics",
            label: "No critical diagnostics",
            passed: !isLive,
            detail: !isLive ? "No open critical findings." : "1 critical finding remains open.",
          },
          {
            id: "execution_validation",
            label: "No execution validation failures",
            passed: true,
            detail: "No zero-value or precision validation failures were recorded.",
          },
          {
            id: "strategy_lifecycle",
            label: "Strategy lifecycle healthy",
            passed: !isLive,
            detail: !isLive ? "No blocked strategies or stalled exits are visible." : "A stalled exit needs review.",
          },
          {
            id: "market_data",
            label: "Market data fresh",
            passed: true,
            detail: "Recent BBO and trade activity look fresh.",
          },
          {
            id: "coinbase",
            label: "Valid Coinbase credentials",
            passed: isLive,
            detail: isLive
              ? "Validated Coinbase connection is ready for balances and trading."
              : "No validated Coinbase connection found.",
          },
          {
            id: "exposure",
            label: "Exposure configured",
            passed: true,
            detail: "At least one strategy has assigned capital.",
          },
          {
            id: "billing",
            label: "Live billing active",
            passed: isLive,
            detail: isLive ? "Trial or subscription covers live trading." : "Live mode still needs a trial or subscription.",
          },
        ],
      },
    },
    positions: [
      {
        id: "pos-btc",
        symbol: "BTC-USD",
        strategy: "Momentum",
        side: "long",
        quantity: "0.44",
        entryPrice: isLive ? 67831 : 67761,
        markPrice: isLive ? 68722 : 68400,
        unrealizedPnl: isLive ? 392 : 281,
        exposure: isLive ? 30237 : 30096,
        openedAt: "2026-04-22T08:15:00Z",
        lastTradeAt: "2026-04-22T10:05:00Z",
        closedAt: null,
        ageMinutes: 240,
        ageHours: 4,
        exitStatus: isLive ? "stalled" : "triggered",
        exitStage: "take_profit_triggered",
        exitReasonCode: isLive ? "exit_stalled" : "take_profit_triggered",
        exitReasonDetail: isLive
          ? "Exit request has been pending too long after the take-profit trigger."
          : "Take-profit guard is armed and ready to close on confirmation.",
        exitUpdatedAt: "2026-04-22T10:10:00Z",
        exitStalled: isLive,
      },
      {
        id: "pos-sol",
        symbol: "SOL-USD",
        strategy: "DCA",
        side: "long",
        quantity: "85",
        entryPrice: isLive ? 169.74 : 170.47,
        markPrice: isLive ? 169.1 : 171.2,
        unrealizedPnl: isLive ? -54 : 62,
        exposure: isLive ? 14374 : 14552,
        openedAt: "2026-04-21T18:40:00Z",
        lastTradeAt: "2026-04-22T07:20:00Z",
        closedAt: null,
        ageMinutes: 1180,
        ageHours: 19.6667,
        exitStatus: "monitoring",
        exitStage: "exit_monitoring_started",
        exitReasonCode: null,
        exitReasonDetail: null,
        exitUpdatedAt: "2026-04-21T18:40:00Z",
        exitStalled: false,
      },
    ],
    activeTrades: [
      {
        id: "trade-1",
        symbol: "ETH-USD",
        strategy: "Momentum",
        status: "partially_filled",
        progressPct: 64,
        submittedAt: "2m ago",
        notional: 4800,
      },
      {
        id: "trade-2",
        symbol: "ADA-USD",
        strategy: "DCA",
        status: "pending",
        progressPct: 22,
        submittedAt: "4m ago",
        notional: 910,
      },
    ],
    recentActivity: [
      {
        id: "activity-1",
        symbol: "BTC-USD",
        side: "buy",
        status: "filled",
        amount: "0.08",
        price: 68310,
        timestamp: "11:22",
      },
      {
        id: "activity-2",
        symbol: "DOGE-USD",
        side: "sell",
        status: "cancelled",
        amount: "4200",
        price: 0.17,
        timestamp: "10:58",
      },
      {
        id: "activity-3",
        symbol: "ETH-USD",
        side: "buy",
        status: "filled",
        amount: "0.63",
        price: 3514,
        timestamp: "09:44",
      },
    ],
    capitalUtilization: {
      totalCapital: isLive ? 42000 : 15000,
      availableCash: isLive ? 18214.64 : 6240.31,
      reservedCash: isLive ? 2100 : 540,
      lockedCapital: isLive ? 21685.36 : 8220.13,
      deployedCapital: isLive ? 23785.36 : 8760.13,
      totalDeployedPct: isLive ? 56.63 : 58.4,
      byStrategy: [
        {
          strategy: "momentum",
          assignedCapital: isLive ? 18900 : 6300,
          availableCash: isLive ? 7400 : 2400,
          reservedCash: isLive ? 900 : 180,
          lockedCapital: isLive ? 10600 : 3720,
          deployedCapital: isLive ? 11500 : 3900,
          utilizationPct: isLive ? 60.85 : 61.9,
        },
        {
          strategy: "dca",
          assignedCapital: isLive ? 11760 : 4200,
          availableCash: isLive ? 5300 : 1980,
          reservedCash: isLive ? 600 : 120,
          lockedCapital: isLive ? 5860 : 2100,
          deployedCapital: isLive ? 6460 : 2220,
          utilizationPct: isLive ? 54.93 : 52.86,
        },
      ],
      avgTradeSizeByStrategy: [
        { strategy: "dca", avgTradeSize: isLive ? 135 : 110 },
        { strategy: "momentum", avgTradeSize: isLive ? 280 : 215 },
      ],
    },
    feeAnalytics: {
      grossPnl: isLive ? 1452.56 : 701.22,
      netPnl: isLive ? 1248.11 : 612.09,
      totalFeesToday: isLive ? 18.42 : 7.11,
      totalFeesWeek: isLive ? 96.33 : 31.28,
      totalFeesMonth: isLive ? 221.9 : 84.47,
      feesByStrategy: [
        { strategy: "momentum", fees: isLive ? 124.5 : 43.2 },
        { strategy: "dca", fees: isLive ? 61.8 : 28.4 },
      ],
      feesBySymbol: [
        { symbol: "BTC-USD", fees: isLive ? 88.2 : 31.7 },
        { symbol: "ETH-USD", fees: isLive ? 56.3 : 22.8 },
      ],
      makerCount: isLive ? 12 : 20,
      takerCount: isLive ? 18 : 9,
      mixedCount: isLive ? 4 : 3,
      avgEstimatedSlippageBps: isLive ? 11.4 : 8.2,
      avgNetEdgeAtEntryBps: isLive ? 46.8 : 61.4,
      skippedTradesDueToFees: isLive ? 7 : 3,
      paperLiveComparison: {
        paper: { fees: 84.47, netPnl: 612.09 },
        live: { fees: 221.9, netPnl: 1248.11 },
      },
    },
    rejectionDiagnostics: {
      totalRejected: isLive ? 12 : 5,
      byStage: [
        { stage: "risk", count: isLive ? 6 : 2 },
        { stage: "suppression", count: isLive ? 4 : 2 },
        { stage: "execution", count: isLive ? 2 : 1 },
      ],
      breakdown: [
        {
          stage: "risk",
          reasonCode: "policy",
          count: isLive ? 4 : 2,
          lastSeenAt: new Date().toISOString(),
          latestDetail: "fee_economics: Expected net edge below threshold",
          strategies: ["momentum", "reversion"],
          symbols: ["BTC-USD", "ETH-USD"],
        },
        {
          stage: "suppression",
          reasonCode: "max_open_positions reached",
          count: isLive ? 3 : 1,
          lastSeenAt: new Date().toISOString(),
          latestDetail: "Strategy suppression blocked new buy",
          strategies: ["day_trading"],
          symbols: ["SOL-USD"],
        },
      ],
      recent: [
        {
          stage: "execution",
          reasonCode: "coinbase_connection",
          reasonDetail: "Coinbase connection is not trade-enabled",
          strategy: "dca",
          symbol: "SOL-USD",
          createdAt: new Date().toISOString(),
        },
        {
          stage: "risk",
          reasonCode: "policy",
          reasonDetail: "fee_economics: Expected net edge below threshold",
          strategy: "momentum",
          symbol: "BTC-USD",
          createdAt: new Date().toISOString(),
        },
      ],
    },
  };
}

export function mockTokens(mode: TradingMode): TokenItem[] {
  const liveOnlyDisabled = mode === "live" ? ["DOGE", "SHIB"] : [];
  return [
    { id: "btc", symbol: "BTC", quote: "USD", name: "Bitcoin", enabled: true, volatility: "medium" },
    { id: "eth", symbol: "ETH", quote: "USD", name: "Ethereum", enabled: true, volatility: "medium" },
    {
      id: "sol",
      symbol: "SOL",
      quote: "USD",
      name: "Solana",
      enabled: true,
      volatility: "high",
    },
    {
      id: "doge",
      symbol: "DOGE",
      quote: "USD",
      name: "Dogecoin",
      enabled: !liveOnlyDisabled.includes("DOGE"),
      volatility: "high",
    },
  ];
}

export function mockAllocation(): AllocationItem[] {
  return [
    { strategyId: "momentum", strategyName: "Momentum", percent: 42, availableCash: 7400 },
    { strategyId: "dca", strategyName: "DCA", percent: 28, availableCash: 4500 },
    { strategyId: "mean-reversion", strategyName: "Mean Reversion", percent: 18, availableCash: 3200 },
    { strategyId: "day-trading", strategyName: "Day Trading", percent: 12, availableCash: 1900 },
  ];
}

export function mockAlerts(): AlertConfig {
  return {
    push: true,
    email: false,
    tradeFilled: true,
    drawdown: true,
    orderFailed: true,
  };
}

export function mockBillingSummary(): BillingSummary {
  return {
    trialStartedAt: null,
    trialEndsAt: null,
    trialActive: false,
    subscriptionStatus: "active",
    stripeSubscriptionId: "sub_ozie_demo",
    currentPeriodEnd: new Date(Date.now() + 1000 * 60 * 60 * 24 * 22).toISOString(),
  };
}

export function mockCoinbaseConnection(): CoinbaseConnection {
  return {
    id: "conn-demo",
    provider: "coinbase",
    apiKeyNameMasked: "orga...89ab",
    validationStatus: "valid",
    healthStatus: "healthy",
    lastValidatedAt: new Date().toISOString(),
    lastHealthCheckAt: new Date().toISOString(),
    lastError: null,
    canTrade: true,
    canReadBalances: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}
